#!/usr/bin/env python
# coding: utf-8

# In[ ]:


count=31
    
p=0
n=0

i=1
while(i <= count):
    num=input("enter number: ")
    if num =="x":
        i=i+(100*100)
    if num !="x":
        num2 = int(num)
        
        if num2 >=0:
            p = p+1
        else:
            n = n+1
    i=i+1
print("positive: ",p)
print("negative: ",n)
